# Generated by Django 3.1.4 on 2021-01-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nodes',
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('', ''), ('DONE', 'Done'), ('CANCELED', 'Canceled'), ('WAITING', 'Waiting')], default='', max_length=10),
        ),
    ]
