# Generated by Django 3.1.4 on 2021-01-16 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0004_auto_20210116_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('NIL', ''), ('BLG', 'Blog'), ('PST', 'Post'), ('BTC', 'Bootcamp'), ('CKL', 'Checklist'), ('HTL', 'Habit List'), ('RLL', 'Ritual List'), ('ITM', 'List Item'), ('FOR', 'Forum'), ('FFF', 'Forcing Function'), ('HBT', 'Habit'), ('III', 'Implementation Intention'), ('REF', 'Reference'), ('SCM', 'Schema'), ('STR', 'Strategy'), ('BRD', 'Board'), ('CON', 'Concern'), ('GOL', 'Goal'), ('JRN', 'Journal'), ('NOT', 'Note'), ('PRT', 'Priority'), ('PRJ', 'Project'), ('RTR', 'Retrospective'), ('WKS', 'Worksheet')], default='NIL', max_length=3),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('', ''), ('DONE', 'Done'), ('CANCELED', 'Canceled'), ('WAITING', 'Waiting'), ('IDEA', 'Idea')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NIL', 'None'), ('EFF', 'Effective'), ('IEF', 'Ineffective'), ('DIF', 'Difficult')], default='NIL', max_length=3)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
