# Generated by Django 3.1.4 on 2021-01-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20210116_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
    ]
