# Generated by Django 3.1.4 on 2021-01-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
